<?php

namespace Database\Seeders\Interface;

use App\Models\Interface\Menu;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menus = [
            [
                'id' => 1,
                'name' => 'Dashboard',
                'url' => '/dashboard',
                'slug' => 'dashboard',
                'icon' => 'fa fa-dashboard',
                'order' => 1,
                'status' => 'active',
                'parent_id' => null,
                'can' => 'view-dashboard',
            ],
            [
                'id' => 2,
                'name' => 'Users',
                'url' => '/user',
                'slug' => 'user.index',
                'icon' => 'fa fa-users',
                'order' => 2,
                'status' => 'active',
                'parent_id' => null,
                'can' => 'view-users',
            ],
            [
                'id' => 3,
                'name' => 'Attendance',
                'url' => '/attendances',
                'slug' => 'attendances',
                'icon' => 'fa-solid fa-calendar',
                'order' => 3,
                'status' => 'active',
                'parent_id' => null,
                'can' => 'view-attendances',
            ],
            [
                'id' => 4,
                'name' => 'Approval Requests',
                'url' => '/approvals',
                'slug' => 'approvals',
                'icon' => 'fas fa-mail-bulk',
                'order' => 4,
                'status' => 'active',
                'parent_id' => null,
                'can' => 'view-approvals',
            ],
            [
                'id' => 5,
                'name' => 'Inventory',
                'url' => '',
                'slug' => 'inventory',
                'icon' => 'fas fa-box-open',
                'order' => 5,
                'status' => 'active',
                'parent_id' => null,
                'can' => 'view-inventory',
            ],
            [
                'id' => 6,
                'name' => 'Inventory Categories',
                'url' => '/inventory/categories',
                'slug' => 'inventory.categories',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 5,
                'can' => 'view-inventory-categories',
            ],
            [
                'id' => 8,
                'name' => 'Inventory Options',
                'url' => '/inventory/options',
                'slug' => 'inventory.options',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 5,
                'can' => 'view-inventory-options',
            ],
            [
                'id' => 9,
                'name' => 'Inventory Brands',
                'url' => '/inventory/brands',
                'slug' => 'inventory.brands',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 5,
                'can' => 'view-inventory-brands',
            ],
            [
                'id' => 10,
                'name' => 'Inventory Statuses',
                'url' => '/inventory/statuses',
                'slug' => 'inventory.statuses',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 5,
                'can' => 'view-inventory-statuses',
            ],
            [
                'id' => 11,
                'name' => 'Inventory Types',
                'url' => '/inventory/types',
                'slug' => 'inventory.types',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 5,
                'can' => 'view-inventory-types',
            ],
            [
                'id' => 12,
                'name' => 'Inventory Shops',
                'url' => '/inventory/shops',
                'slug' => 'inventory.shops',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 5,
                'can' => 'view-inventory-shops',
            ],
            [
                'id' => 13,
                'name' => 'Inventory Warehouses',
                'url' => '/inventory/warehouses',
                'slug' => 'inventory.warehouses',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 5,
                'can' => 'view-inventory-warehouses',
            ],
            [
                'id' => 14,
                'name' => 'Inventory Products',
                'url' => '/inventory/products',
                'slug' => 'inventory.products',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 5,
                'can' => 'view-inventory-products',
            ],
            [
                'id' => 7,
                'name' => 'Masters',
                'url' => '',
                'slug' => 'masters',
                'icon' => 'fa-solid fa-screwdriver-wrench',
                'order' => 6,
                'status' => 'active',
                'parent_id' => null,
                'can' => 'view-master',
            ],
            [
                'id' => 15,
                'name' => 'Departments',
                'url' => '/departments',
                'slug' => 'departments',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 7,
                'can' => 'view-master-departments',
            ],
            [
                'id' => 16,
                'name' => 'Designations',
                'url' => '/designations',
                'slug' => 'designations',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 7,
                'can' => 'view-master-designations',
            ],
            [
                'id' => 17,
                'name' => 'Roles',
                'url' => '/roles',
                'slug' => 'roles',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 7,
                'can' => 'view-master-roles',
            ],
            [
                'id' => 18,
                'name' => 'Shifts',
                'url' => '/shifts',
                'slug' => 'shifts',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 7,
                'can' => 'view-master-shifts',
            ],
            [
                'id' => 19,
                'name' => 'Teams',
                'url' => '/teams',
                'slug' => 'teams',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 7,
                'can' => 'view-master-teams',
            ],
            [
                'id' => 20,
                'name' => 'Menus',
                'url' => '/interfaces/menus',
                'slug' => 'menus',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 7,
                'can' => 'view-master-menus',
            ],
            [
                'id' => 21,
                'name' => 'Leave Types',
                'url' => '/leavetypes',
                'slug' => 'leavetypes',
                'icon' => 'fas fa-circle',
                'order' => 1,
                'status' => 'active',
                'parent_id' => 7,
                'can' => 'view-master-leavetypes',
            ],
        ];

        Menu::insert($menus);
    }
}
